services:
  vripper:
    container_name: vripper
    image: stoutsock/vripper-project:3.5.4
    ports:
      - "8080:8080/tcp"
    volumes:
      - "./data:/vripper/data"
      - "./downloads:/downloads"
    restart: "unless-stopped"
